### ISSUE TITLE
no file extension in  download

### ISSUE THREAD

**Issue by chadul** [PXgamer/youtube-dl-php#7]
there are no extension in  download, it's return "videoplayback"  can you please fix it?

demo: https://youtube-dl-php.pxgamer.xyz/results.php?id=https%3A%2F%2Fm.youtube.com%2Fwatch%3Fv%3DfyaI4-5849w

**Comment by owenvoke** [comment]
I can't fix this as it is not an issue with this package. The reason this happens is because of a 403 (Forbidden) response from YouTube.

This is a well known part of YouTube's protection for monetised videos.

Please see #6 and #4 for more information. If you do find a way to bypass this, feel free to make a PR.
